# Generated by Django 5.2 on 2025-05-12 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_player_id_alter_player_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guild_players",
                to="db.guild",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="race",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
