# Generated by Django 5.2 on 2025-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_alter_player_guild_alter_race_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="bio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="race",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
